import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleContext } from "@/context/GoogleContext";
import { Toaster } from "react-hot-toast";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryCustom } from "@/context/ReactQueryCustom";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <ReactQueryCustom>
          <GoogleContext>
            <Toaster />
            {children}
          </GoogleContext>
        </ReactQueryCustom>
      </body>
    </html>
  );
}
